### ISSUE TITLE
why not the node sdk?

### ISSUE THREAD

**Issue by mjhaller** [tlianza/pigeon#4]
For folks new to Workers, I'm curious as to why one would use this library, vs. the [node Sentry SDK.](https://www.npmjs.com/package/@sentry/node).  I haven't tried that one, yet, but I don't see a reason it wouldn't work, per https://developers.cloudflare.com/workers/archive/writing-workers/using-npm-modules/

I could see a case for the size of the library though, as it is best to keep workers very light.  Is that the main reason?  Or, is there something deeper I'm missing that wouldn't work in production, which lead to the creation of this project.

Thank you!

**Comment by tlianza** [comment]
Yes, there is something deeper that doesn't work in production - how you make subrequests from a worker using `fetch`:
https://github.com/tlianza/pigeon/blob/master/pigeon-backend.js#L249

**Comment by mjhaller** [comment]
I'm not sure I understand.  You can absolutely make subrequests from a worker.  And, the node client does using `fetch` : https://github.com/getsentry/sentry-javascript/blob/2d628c30036e2ffaad3160a471c4561413484a5b/packages/browser/src/transports/fetch.ts#L42

**Comment by tlianza** [comment]
That's calling the fetch _method_ on an object that I don't believe is available in the workers environment. But, if you see that work in the workers environment that'd be interesting indeed. Let me know how it goes for you and I'd be happy to refer folks to that.
